package src;
import java.util.*;

/**
 *
 * @author sirelvis
 */
public class NewJDialog extends javax.swing.JDialog {
    private ArrayList<String> names;
    private ArrayList<Double> math, eng, sci, soc, ict, bdt, fre, twi, rme;
    private ArrayList<Double> totals;
    private SortedArrayList<Double> sorted;
    public static String schoolName, className, teacherName;
    private String content;
   
    /**
     * Creates new form NewJDialog
     */
    public NewJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        names = new ArrayList();
        math = new ArrayList();
        eng = new ArrayList();
        sci = new ArrayList();
        soc = new ArrayList();
        ict = new ArrayList();
        bdt = new ArrayList();
        fre = new ArrayList();
        twi = new ArrayList();
        rme = new ArrayList();
        totals = new ArrayList();
        sorted = new SortedArrayList();
        teacherName = Welcome.teacherName;
        schoolName = Welcome.schoolName;
        className = Welcome.className;
        content = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jTextField2 = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        notification = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");
        jRadioButtonMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonMenuItem1MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("eReport Application");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setFont(new java.awt.Font("Constantia", 0, 10)); // NOI18N
        setForeground(java.awt.Color.white);
        setIconImage(null);
        setMaximumSize(new java.awt.Dimension(507, 563));

        jTextField2.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jTextField2.setToolTipText("Name of student");

        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Constantia", 0, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 0, 204));
        label1.setName(""); // NOI18N
        //label1.setText(Welcome.schoolName);

        label2.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 0, 204));
        label2.setText("Name");

        jTextField3.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jTextField3.setToolTipText("Score in Mathematics");

        jTextField4.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jTextField4.setToolTipText("Score in BDT");

        jTextField5.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jTextField5.setToolTipText("Score in English");

        jTextField6.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jTextField6.setToolTipText("Score in Science");

        jTextField7.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jTextField7.setToolTipText("Score in Social Studies");

        jTextField8.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jTextField8.setToolTipText("Score in ICT");

        jTextField9.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jTextField9.setToolTipText("Score in Twi");

        jTextField10.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jTextField10.setToolTipText("Score in RME");

        jTextField11.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jTextField11.setToolTipText("Score in French");

        label3.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(0, 51, 204));
        label3.setText("Science");

        label4.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(0, 0, 204));
        label4.setText("Maths");

        label5.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(0, 51, 204));
        label5.setText("English");

        label6.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        label6.setForeground(new java.awt.Color(0, 51, 204));
        label6.setText("Social");

        label7.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        label7.setForeground(new java.awt.Color(0, 51, 204));
        label7.setText("Twi");

        label8.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        label8.setForeground(new java.awt.Color(0, 51, 204));
        label8.setText("ICT");

        label9.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        label9.setForeground(new java.awt.Color(0, 51, 204));
        label9.setText("RME");

        label10.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        label10.setForeground(new java.awt.Color(0, 51, 204));
        label10.setText("BDT");

        label11.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        label11.setForeground(new java.awt.Color(0, 51, 204));
        label11.setText("French");

        jButton1.setFont(new java.awt.Font("Constantia", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Back");

        jButton2.setFont(new java.awt.Font("Constantia", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("Save");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Constantia", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 51));
        jButton3.setText("Done");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        notification.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        notification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(notification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(notification, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jRadioButtonMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {                                      

        try{
        if   (!((Double.parseDouble(jTextField3.getText()) < 0 || Double.parseDouble(jTextField3.getText()) > 100) || 
                (Double.parseDouble(jTextField5.getText()) < 0 || Double.parseDouble(jTextField5.getText()) > 100) ||
                (Double.parseDouble(jTextField6.getText()) < 0 || Double.parseDouble(jTextField6.getText()) > 100) ||
                (Double.parseDouble(jTextField7.getText()) < 0 || Double.parseDouble(jTextField7.getText()) > 100) ||
                (Double.parseDouble(jTextField9.getText()) < 0 || Double.parseDouble(jTextField9.getText()) > 100) ||
                (Double.parseDouble(jTextField11.getText()) < 0 || Double.parseDouble(jTextField11.getText()) > 100) ||
                (Double.parseDouble(jTextField10.getText()) < 0 || Double.parseDouble(jTextField10.getText()) > 100) ||
                (Double.parseDouble(jTextField4.getText()) < 0 || Double.parseDouble(jTextField4.getText()) > 100) ||
                (Double.parseDouble(jTextField8.getText()) < 0 || Double.parseDouble(jTextField8.getText()) > 100))){
        	//jTextField3.setText("Enter number between 0 and 100");
        		names.add(jTextField2.getText());
                math.add(Double.parseDouble(jTextField3.getText()));
                eng.add(Double.parseDouble(jTextField5.getText()));
                sci.add(Double.parseDouble(jTextField6.getText()));
                soc.add(Double.parseDouble(jTextField7.getText()));
                twi.add(Double.parseDouble(jTextField9.getText()));
                fre.add(Double.parseDouble(jTextField11.getText()));
                rme.add(Double.parseDouble(jTextField10.getText()));
                bdt.add(Double.parseDouble(jTextField4.getText()));
                ict.add(Double.parseDouble(jTextField8.getText()));
                double t = Double.parseDouble(jTextField3.getText()) + 
                		Double.parseDouble(jTextField5.getText()) + 
                		Double.parseDouble(jTextField6.getText()) +
                		Double.parseDouble(jTextField7.getText()) +
                		Double.parseDouble(jTextField9.getText()) +
                		Double.parseDouble(jTextField11.getText()) +
                		Double.parseDouble(jTextField10.getText()) +
                		Double.parseDouble(jTextField4.getText()) +
                		Double.parseDouble(jTextField8.getText());
                totals.add(t);
                sorted.insert(t);
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
                jTextField10.setText("");
                jTextField11.setText("");
                //label1.setText("NEW WORLD SCHOOL");
        
        }
        else
            notification.setText("Please enter numbers between 0 and 100!");         
    	}
    	catch(Exception e){notification.setText("Enter numbers between 0 and 100!");}
    	finally {}        
        
    }                                     

    @SuppressWarnings("deprecation")
	private void jButton3MouseClicked(java.awt.event.MouseEvent evt) { 
        System.out.printf("%-35s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %-8s %-8s","Name","Maths", "English", "Science", "Social", "Twi", "French", "ICT", "BDT", "RME","TOTAL","POSITION");
        System.out.println();
        content = content + "Name \t\t\t" + "Maths \t" + "English \t" + "Science \t" + "Social \t" + "Twi \t" + "French \t" + "ICT \t" + "BDT \t" + "RME \t" + "TOTAL \t" + "POSITION \n";
        for(int i=0; i<names.size(); i++){
            System.out.printf("%-35s ",names.get(i));
            
            System.out.printf("%-8s ",math.get(i));
            System.out.printf("%-8s ",eng.get(i));
            System.out.printf("%-8s ",sci.get(i));
            System.out.printf("%-8s ",soc.get(i));
            System.out.printf("%-8s ",twi.get(i));
            System.out.printf("%-8s ",fre.get(i));
            System.out.printf("%-8s ",ict.get(i));
            System.out.printf("%-8s ",bdt.get(i));
            System.out.printf("%-8s ",rme.get(i));
            System.out.printf("%-8s ",totals.get(i));
            System.out.printf("%-8s ",sorted.find(totals.get(i)) + 1);
            System.out.println();
            content = content + names.get(i) + "\t\t\t" + math.get(i) + "\t" + eng.get(i)+ "\t" + sci.get(i) + "\t"+ soc.get(i) + "\t"+ twi.get(i) + "\t"+ fre.get(i) + "\t"+ ict.get(i)+ "\t" + bdt.get(i) + "\t"+ rme.get(i)+ "\t" + totals.get(i) + "\t"+ (sorted.find(totals.get(i)) + 1) + "\n" ;
            this.show(false);
        }
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                eReport dialog = new eReport(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });

                dialog.jTextArea1.setText(content);
                dialog.setVisible(true);
            }
        });
        //return content;
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    public java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JLabel notification;
    // End of variables declaration                   
}
